// Global styles first: the font @import must come before any other CSS rule.
import './styles/global.scss'
// eslint-disable-next-line import/no-unresolved -- generated by config/vite/designSystem.ts
import 'virtual:rl-tokens.css'

import type { AvatarProps } from './components/Avatar'
import type { ButtonProps } from './components/Button'
import type { CheckboxProps } from './components/Checkbox'
import type { DatePickerProps } from './components/DatePicker'
import type { DialogProps } from './components/Dialog'
import type { GroupButtonsProps } from './components/GroupButtons'
import type { InputProps } from './components/Input'
import type { LinkProps } from './components/Link'
import type { ModalProps } from './components/Modal'
import type { MultiSelectProps } from './components/MultiSelect'
import type { PaginationProps } from './components/Pagination'
import type { PillProps } from './components/Pill'
import type { PopOverProps } from './components/PopOver'
import type { RadioProps } from './components/Radio'
import type { SelectProps } from './components/Select'
import type { LabelProps } from './components/shared/Label'
import type {
  TableProps,
  ColumnDef,
  SortingState,
  ColumnSort,
} from './components/Table'
import type { TabsProps } from './components/Tabs'
import type { TagProps } from './components/Tag'
import type { TextProps } from './components/Text'
import type { TextAreaProps } from './components/TextArea'
import type { TimePickerProps } from './components/TimePicker'
import type { ToggleProps } from './components/Toggle'
import type { TooltipProps } from './components/Tooltip'
import type { UploadProps } from './components/Upload'
import type { ColorType } from './theme'

import alert, { ToastContainer } from './components/Alert'
import Avatar, { avatarSelector } from './components/Avatar'
import Button, { buttonSelector } from './components/Button'
import Checkbox, { checkboxSelector } from './components/Checkbox'
import DatePicker, { datePickerSelector } from './components/DatePicker'
import Dialog from './components/Dialog'
import GroupButtons, { groupButtonsSelector } from './components/GroupButtons'
import Input, { inputSelector } from './components/Input'
import Link, { linkSelector } from './components/Link'
import Modal from './components/Modal'
import MultiSelect from './components/MultiSelect'
import Pagination, { paginationSelector } from './components/Pagination'
import Pill, { pillSelector } from './components/Pill'
import PopOver, { popOverSelector } from './components/PopOver'
import Radio, { radioSelector } from './components/Radio'
import Select, { selectSelector } from './components/Select'
import Label, { labelSelector } from './components/shared/Label'
import Table, {
  defaultColumnOptions,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getSortedRowModel,
  useReactTable,
  createColumnHelper,
  tableSelector,
} from './components/Table'
import Tabs, { tabsSelector } from './components/Tabs'
import Tag, { tagSelector } from './components/Tag'
import Text, { textSelector } from './components/Text'
import TextArea, { textAreaSelector } from './components/TextArea'
import TimePicker, { timePickerSelector } from './components/TimePicker'
import Toggle, { toggleSelector } from './components/Toggle'
import Tooltip from './components/Tooltip'
import Upload, { uploadSelector } from './components/Upload'
import Flex, { flexSelector } from './elements/Flex'
import {
  setupTheme,
  theme,
  colorOptions,
  getColor,
} from './theme'

export type {
  AvatarProps,
  ButtonProps,
  CheckboxProps,
  DatePickerProps,
  DialogProps,
  GroupButtonsProps,
  InputProps,
  LinkProps,
  ModalProps,
  MultiSelectProps,
  PaginationProps,
  PillProps,
  PopOverProps,
  RadioProps,
  SelectProps,
  LabelProps,
  TableProps,
  TabsProps,
  TagProps,
  TextProps,
  TextAreaProps,
  TimePickerProps,
  ToggleProps,
  TooltipProps,
  UploadProps,
  ColorType,
}

export {
  setupTheme,
  theme,
  colorOptions,
  getColor,
}

export {
  // Alert imports
  alert,
  ToastContainer,
  // Components imports
  Avatar,
  Button,
  Checkbox,
  DatePicker,
  Dialog,
  GroupButtons,
  Input,
  Link,
  Modal,
  MultiSelect,
  Pagination,
  Pill,
  PopOver,
  Radio,
  Select,
  // Table imports
  Table,
  defaultColumnOptions,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getSortedRowModel,
  useReactTable,
  createColumnHelper,
  ColumnDef,
  SortingState,
  ColumnSort,
  //
  Tabs,
  Tag,
  TextArea,
  TimePicker,
  Toggle,
  Tooltip,
  Upload,
  Text,
  Label,
  Flex,
}

// Root-element selectors, to style components from the outside (`${buttonSelector} { ... }`).
export {
  avatarSelector,
  buttonSelector,
  checkboxSelector,
  datePickerSelector,
  flexSelector,
  groupButtonsSelector,
  inputSelector,
  labelSelector,
  linkSelector,
  paginationSelector,
  pillSelector,
  popOverSelector,
  radioSelector,
  selectSelector,
  tableSelector,
  tabsSelector,
  tagSelector,
  textAreaSelector,
  textSelector,
  timePickerSelector,
  toggleSelector,
  uploadSelector,
}
